services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    network_mode: host
    restart: always

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    network_mode: host
    volumes:
      - ./mysql-exporter.cnf:/etc/mysql-exporter.cnf:ro
    command:
      - "--config.my-cnf=/etc/mysql-exporter.cnf"
    restart: always

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    network_mode: host
    environment:
      DATA_SOURCE_NAME: "postgresql://pguser:pg123@localhost:5432/samplepgdb?sslmode=disable"
    restart: always