- name: Install and Configure MySQL
  hosts: private
  become: yes

  vars:
    mysql_db: sampledb
    mysql_user: appuser
    mysql_password: apppass

  tasks:

    - name: Install MySQL and dependencies
      apt:
        name:
          - mysql-server
          - python3-pymysql
        state: present
        update_cache: yes

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database
      community.mysql.mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create application user
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create employees table safely
      community.mysql.mysql_query:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_db: "{{ mysql_db }}"
        query: |
          CREATE TABLE IF NOT EXISTS employees (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(100),
            role VARCHAR(100)
          );

    - name: Insert sample data safely
      shell: |
       mysql -u root -S /var/run/mysqld/mysqld.sock {{ mysql_db }} <<EOF
       INSERT INTO employees (name, role)
       SELECT 'Jayani', 'DevOps Engineer'
       WHERE NOT EXISTS (
         SELECT 1 FROM employees WHERE name='Jayani'
       );

       INSERT INTO employees (name, role)
       SELECT 'Admin', 'DB Admin'
       WHERE NOT EXISTS (
          SELECT 1 FROM employees WHERE name='Admin'
       );
       EOF
      args:
       executable: /bin/bash